import type { Metadata } from "next";
import Model from "@/components/Model";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by Olutech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        <Model />
        {children}
      </body>
    </html>
  );
}
